### ISSUE TITLE
updateIssue fatal error

### ISSUE THREAD

**Issue by dimd13** [sotarok/node-redmine#6]
Hi, method updateIssue returns an empty string and JSON.parse cannot be applied to empty strings in request method, this causes an error:

```
undefined:0


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/user/Projects/feedMiner/node_modules/redmine/lib/redmine.js:89:23)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Sorry 4 my english

**Comment by guilhermesperb** [comment]
I performed a commit to fix it

Sorry 4 my english too :)
